language: node_js
sudo: true
node_js:
- '8'

before_install:
- npm install exp --global
- pip install --user awscli
install:
- make install

script:
- make lint
- make test

after_success:
- make test-deploy
- make production-deploy

notifications:
  email: false
  webhooks: http://requestbin.fullcontact.com/193rc4r1

